# Quantum Computing: Complete Mastery
## Module 2: Quantum Circuits & Quantum Information

---

##  Welcome to Module 2!

In **Module 1**, you mastered the foundations:
- ✅ Qubits as vectors
- ✅ Quantum gates as unitary matrices
- ✅ Bloch sphere visualization
- ✅ Multi-qubit systems and tensor products
- ✅ Entanglement and Bell states
- ✅ Building and executing circuits with Qiskit

**Now we level up.**

Module 2 takes those foundations and builds **real quantum algorithms** and **quantum information protocols**. You'll learn how quantum mechanics enables tasks that are **impossible classically**.

---

##  What You'll Master in Module 2

### 1. **Advanced Circuit Techniques** (Cells 2-4)
- Multi-qubit controlled gates (Toffoli, multi-control)
- Circuit composition and decomposition
- Inverse circuits and uncomputation
- Barrier usage and circuit optimization
- Parameterized circuits

### 2. **Quantum Teleportation** (Cells 5-7)
- The complete protocol step-by-step
- Why it doesn't violate relativity
- Implementation in Qiskit
- Verification with statevector
- Connection to entanglement and measurement

### 3. **Superdense Coding** (Cells 8-9)
- Sending 2 classical bits with 1 qubit
- The reverse of teleportation
- Implementation and verification
- Information theory implications

### 4. **Phase Kickback** (Cells 10-11)
- How controlled gates affect control qubits
- The mechanism behind many quantum algorithms
- Visualizing phase changes
- Setting up for Deutsch-Jozsa

### 5. **Deutsch-Jozsa Algorithm** (Cells 12-14)
- First quantum algorithm with exponential speedup
- Constant vs balanced functions
- Oracle implementation
- Complete walkthrough and verification

### 6. **Bernstein-Vazirani Algorithm** (Cells 15-16)
- Finding hidden bit strings
- One query vs n queries classically
- Oracle design
- Implementation from scratch

### 7. **Quantum Fourier Transform (QFT)** (Cells 17-19)
- Introduction to QFT (foundation for Shor's algorithm)
- Mathematical formulation
- Circuit implementation
- Differences from classical FFT

---

## 📊 Module Roadmap

| Section | Cells | Topic | Key Concept |
|---------|-------|-------|-------------|
| **Part 1** | 2-4 | Advanced Circuits | Multi-control, composition |
| **Part 2** | 5-7 | Teleportation | Entanglement + measurement |
| **Part 3** | 8-9 | Superdense Coding | 2 bits in 1 qubit |
| **Part 4** | 10-11 | Phase Kickback | Eigenstate magic |
| **Part 5** | 12-14 | Deutsch-Jozsa | First quantum advantage |
| **Part 6** | 15-16 | Bernstein-Vazirani | Hidden string finding |
| **Part 7** | 17-19 | QFT Introduction | Foundation for Shor's |

---

##  What's Coming in Later Modules

**Module 3:** Grover's Algorithm (unstructured search)  
**Module 4:** Shor's Algorithm (factoring, breaking RSA)  
**Module 5:** VQE & QAOA (near-term quantum computers)  
**Module 6:** Quantum Chemistry (molecular simulation)  
**Module 7:** Error Correction (fault-tolerant quantum computing)  
**Module 8:** Quantum Machine Learning  
**Module 9:** Real Hardware (IBM Quantum)  

---

## Multi-Qubit Controlled Gates

### Beyond CNOT: Controlling with Multiple Qubits

In Module 1, we learned about **CNOT** (Controlled-NOT):
- 1 control qubit
- 1 target qubit
- Operation: "If control = |1⟩, flip target"

**Now we generalize:** What if we need **multiple** control qubits?

---

## The Toffoli Gate (CCNOT)

### Definition

The **Toffoli gate** (also called CCNOT or Controlled-Controlled-NOT) has:
- **2 control qubits**
- **1 target qubit**
- **Operation:** Flip target ONLY if BOTH controls are |1⟩

**Notation:**
- Mathematical: CCNOT
- Qiskit: `ccx(control1, control2, target)`
- Also called: Toffoli gate (after Tommaso Toffoli)

### Truth Table

| Control 1 | Control 2 | Target In | Target Out |
|-----------|-----------|-----------|------------|
| 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 |
| 0 | 1 | 0 | 0 |
| 0 | 1 | 1 | 1 |
| 1 | 0 | 0 | 0 |
| 1 | 0 | 1 | 1 |
| **1** | **1** | **0** | **1** ← Only this case flips |
| **1** | **1** | **1** | **0** ← Only this case flips |

Target flips **if and only if** control1 = 1 **AND** control2 = 1

---

## Circuit Diagram
```
q_0: ──■──  ← Control 1
       │
q_1: ──■──  ← Control 2
     ┌─┴─┐
q_2: ┤ X ├  ← Target
     └───┘
```

**Reading the diagram:**
- Two black dots (■) = two controls
- X gate at bottom = target gets flipped
- Vertical lines connect them

---

## Matrix Representation

For 3 qubits (8×8 matrix), the Toffoli gate is:

$$\text{CCNOT} = \begin{pmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
\end{pmatrix}$$

**Structure:**
- Almost identity matrix
- Only the last 2×2 block (bottom-right) is swapped
- This corresponds to |110⟩ ↔ |111⟩

**Basis state mapping:**
```
|000⟩ → |000⟩  (no change)
|001⟩ → |001⟩  (no change)
|010⟩ → |010⟩  (no change)
|011⟩ → |011⟩  (no change)
|100⟩ → |100⟩  (no change)
|101⟩ → |101⟩  (no change)
|110⟩ → |111⟩  ← Flip (both controls = 1)
|111⟩ → |110⟩  ← Flip (both controls = 1)
```

---

## Why Toffoli is Important

### 1. **Classical Reversible Computing**

Toffoli gate is **universal for classical reversible computing**!

**Example: AND gate**
```
Controls: a, b (inputs)
Target: initialized to |0⟩

After Toffoli:
Target = a AND b
```

**Example: NAND gate** (universal for all classical logic)
```
Controls: a, b
Target: initialized to |1⟩

After Toffoli:
Target = NOT(a AND b) = a NAND b
```

**This means:** Any classical circuit can be built from Toffoli gates!

### 2. **Quantum Algorithms**

Used in:
- **Grover's algorithm** (diffusion operator)
- **Shor's algorithm** (modular exponentiation)
- **Quantum arithmetic** (adders, multipliers)
- **Error correction** (syndrome measurement)

### 3. **Uncomputation**

Cleaning up "garbage" qubits while preserving quantum information:
```
Compute something → Store in ancilla
Use the result
Uncompute (reverse) → Clean ancilla back to |0⟩
```

Toffoli is self-inverse: Applying it twice gets you back to the start.

---

## Multi-Control Gates (General Case)

### Beyond 2 Controls

What if we need **3, 4, or more** control qubits?

**General form:**
- $n$ control qubits
- 1 target qubit
- Target flips **only if ALL** controls = |1⟩

**Examples:**
- 3 controls: C³X (Controlled-Controlled-Controlled-X)
- 4 controls: C⁴X
- $n$ controls: CⁿX

### Circuit Diagram Examples

**3 controls (C³X):**
```
q_0: ──■──
       │
q_1: ──■──
       │
q_2: ──■──
     ┌─┴─┐
q_3: ┤ X ├
     └───┘
```

**4 controls (C⁴X):**
```
q_0: ──■──
       │
q_1: ──■──
       │
q_2: ──■──
       │
q_3: ──■──
     ┌─┴─┐
q_4: ┤ X ├
     └───┘
```

### Qiskit Implementation
```python
# Toffoli (2 controls)
qc.ccx(control1, control2, target)

# Multi-control (n controls)
qc.mcx([control1, control2, ..., controln], target)
```

---

## Controlled-U Gates (General)

### Beyond Controlled-X

We can make **any** gate controlled!

**Controlled-H:**
```
Control: If |1⟩, apply H to target
Target: Gets H applied (or not)
```

**Controlled-Z:**
```
Both qubits symmetric (Z is diagonal)
Actually equivalent to CZ gate from Module 1
```

**Controlled-arbitrary-U:**
```python
# Any unitary U can be controlled
from qiskit.circuit.library import UnitaryGate

U = np.array([...])  # Your matrix
cu = UnitaryGate(U).control(1)  # Make it controlled
qc.append(cu, [control, target])
```

---

## Properties of Multi-Control Gates

### 1. **Reversibility**

All quantum gates are reversible, including multi-control:

$$\text{CCNOT}^{-1} = \text{CCNOT}$$
$$\text{CCNOT} \cdot \text{CCNOT} = I$$

Toffoli is **self-inverse** (its own inverse).

### 2. **Unitarity**

$$\text{CCNOT}^\dagger \text{CCNOT} = I$$

Preserves norm (as all quantum gates must).

### 3. **Decomposition**

Multi-control gates can be decomposed into:
- Single-qubit gates
- CNOT gates
- Sometimes requires ancilla qubits

**Example:** CCNOT can be built from 6 CNOTs + single-qubit gates.

(We'll see this decomposition in the code cell)

---

## Circuit Depth Considerations

### What is Circuit Depth?

**Depth** = longest path through the circuit (counting gate layers)

**Example:**
```
     ┌───┐
q_0: ┤ H ├──■──       Depth = 2
     └───┘┌─┴─┐       Layer 1: H
q_1: ─────┤ X ├       Layer 2: CNOT
          └───┘
```

### Why Depth Matters

**On real quantum hardware:**
- Gates take time to execute
- Qubits **decohere** (lose quantum information) over time
- Shallow circuits = less decoherence = more accurate

**Goal:** Minimize circuit depth for real hardware.

### Multi-Control Depth Trade-off

**Native Toffoli:** Depth = 1 (if hardware supports it directly)

**Decomposed Toffoli:** Depth ≈ 5-10 (when built from CNOTs)

**Multi-control with $n$ controls:**
- Naive decomposition: Depth ∝ $2^n$ (exponential!)
- Optimized with ancillas: Depth ∝ $n$ (linear!)

**Trade-off:** More ancilla qubits → shallower circuit

---

## Ancilla Qubits

### What Are Ancilla Qubits?

**Ancilla** (Latin for "helper") = Extra qubits used temporarily

**Purpose:**
- Help implement complex gates
- Reduce circuit depth
- Store intermediate results

**Key property:** Must be returned to initial state (|0⟩) by the end
- Otherwise they become "entangled garbage"

### Example: C³X with Ancilla

**Without ancilla:**
```
Requires ~24 CNOTs
Depth ≈ 8
```

**With 1 ancilla:**
```
Requires ~12 CNOTs
Depth ≈ 5
```

**Trade-off:** 1 extra qubit → 40% faster circuit

---

## Visual Summary

### Family of Controlled Gates
```
NOT (X)         →  Single qubit, no control
  ↓
CNOT (CX)       →  1 control, 1 target
  ↓
CCNOT (CCX)     →  2 controls, 1 target
  ↓
C³X             →  3 controls, 1 target
  ↓
CⁿX             →  n controls, 1 target
```

### Control Structure
```
1 control:   ──●──      (CNOT)
             ┌─┴─┐
             ┤ X ├
             └───┘

2 controls:  ──■──      (Toffoli)
               │
             ──■──
             ┌─┴─┐
             ┤ X ├
             └───┘

n controls:  ──■──      (McX)
               │
             ──■──
               │
              ...
               │
             ──■──
             ┌─┴─┐
             ┤ X ├
             └───┘
```

---

## What's Next?

In the code cell, we'll:

1. **Implement Toffoli gate** from scratch (NumPy)
2. **Verify the truth table** computationally
3. **Use Qiskit's CCX gate**
4. **Build multi-control gates** with `mcx()`
5. **Decompose Toffoli** into CNOTs
6. **Compare circuit depths**
7. **Implement controlled-U** for arbitrary gates

**You'll gain complete mastery of multi-qubit control operations.**

These are essential for every quantum algorithm we'll build in this module!

In [2]:
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit_aer import AerSimulator
from qiskit.quantum_info import Statevector, Operator
from qiskit.visualization import plot_histogram
import numpy as np
import matplotlib.pyplot as plt

print("="*70)
print("MULTI-QUBIT CONTROLLED GATES")
print("="*70)

# ============================================================================
# PART 1: TOFFOLI GATE FROM SCRATCH (NUMPY)
# ============================================================================

print("\n" + "="*70)
print("PART 1: TOFFOLI GATE - BUILDING THE MATRIX")
print("="*70)

# ----------------------------------------------------------------------------
# Constructing the 8x8 Toffoli matrix
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Building Toffoli (CCNOT) Matrix")
print("-"*70)

# Toffoli is an 8x8 matrix (3 qubits = 2^3 = 8 basis states)
# It swaps |110⟩ ↔ |111⟩, leaves others unchanged

CCNOT = np.eye(8, dtype=complex)

# Swap the last two rows (indices 6 and 7)
# |110⟩ = state 6, |111⟩ = state 7
CCNOT[6, 6] = 0
CCNOT[6, 7] = 1
CCNOT[7, 6] = 1
CCNOT[7, 7] = 0

print("\nToffoli (CCNOT) matrix:")
print(CCNOT.real.astype(int))  # Real parts only (all integers)

print("\nStructure:")
print("  - Mostly identity (7x7 block)")
print("  - Only last 2x2 block is swapped")
print("  - This corresponds to flipping target when both controls = |1⟩")

# Verify it's unitary
print("\n" + "-"*70)
print("Verifying Unitarity")
print("-"*70)

is_unitary = np.allclose(CCNOT @ CCNOT.conj().T, np.eye(8))
print(f"\nCCNOT is unitary: {is_unitary} ✓")

# Verify it's self-inverse
is_self_inverse = np.allclose(CCNOT @ CCNOT, np.eye(8))
print(f"CCNOT is self-inverse: {is_self_inverse} ✓")
print("  (Applying Toffoli twice returns to original state)")

# ----------------------------------------------------------------------------
# Verifying the truth table
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Verifying Truth Table")
print("-"*70)

print("\nTesting all 8 basis states:")
print("\n{:^15} | {:^15} | {:^10}".format("Input", "Output", "Changed?"))
print("-" * 45)

for i in range(8):
    # Create basis state |i⟩
    input_state = np.zeros(8)
    input_state[i] = 1
    
    # Apply Toffoli
    output_state = CCNOT @ input_state
    
    # Find which basis state we got
    output_index = np.argmax(np.abs(output_state))
    
    # Convert to binary
    input_binary = format(i, '03b')
    output_binary = format(output_index, '03b')
    
    changed = "✓ YES" if i != output_index else "No"
    
    print("{:^15} | {:^15} | {:^10}".format(
        f"|{input_binary}⟩",
        f"|{output_binary}⟩",
        changed
    ))

print("\nObservation:")
print("  Only |110⟩ and |111⟩ change (both controls = 1)")
print("  This is exactly what we expect from CCNOT!")

# ============================================================================
# PART 2: TOFFOLI IN QISKIT
# ============================================================================

print("\n" + "="*70)
print("PART 2: TOFFOLI GATE IN QISKIT")
print("="*70)

# ----------------------------------------------------------------------------
# Basic Toffoli circuit
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Creating Toffoli Circuit")
print("-"*70)

qc = QuantumCircuit(3)
qc.ccx(0, 1, 2)  # Control: 0, 1; Target: 2

print("\nCircuit:")
print(qc.draw(output='text'))

print("\nQiskit notation:")
print("  qc.ccx(control1, control2, target)")
print("  '■' symbols = controls")
print("  'X' at bottom = target")

# Get the matrix representation from Qiskit
qiskit_ccnot = Operator(qc).data

print("\n" + "-"*70)
print("Comparing NumPy vs Qiskit")
print("-"*70)

match = np.allclose(CCNOT, qiskit_ccnot)
print(f"\nNumPy CCNOT matches Qiskit: {match} ✓")

if match:
    print("  Our manual implementation is identical to Qiskit's!")

# ----------------------------------------------------------------------------
# Testing Toffoli with different initial states
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Testing Toffoli with Different Initial States")
print("-"*70)

test_cases = [
    ("000", [0, 0, 0], "Both controls = 0"),
    ("001", [0, 0, 1], "Both controls = 0"),
    ("010", [0, 1, 0], "One control = 1"),
    ("011", [0, 1, 1], "One control = 1"),
    ("100", [1, 0, 0], "One control = 1"),
    ("101", [1, 0, 1], "One control = 1"),
    ("110", [1, 1, 0], "Both controls = 1 → FLIP"),
    ("111", [1, 1, 1], "Both controls = 1 → FLIP"),
]

print("\nTesting each case:")
for label, init, description in test_cases:
    qc = QuantumCircuit(3)
    
    # Initialize state
    for i, val in enumerate(init):
        if val == 1:
            qc.x(i)
    
    # Apply Toffoli
    qc.ccx(0, 1, 2)
    
    # Get final state
    final_state = Statevector(qc)
    
    # Find the basis state with amplitude 1
    final_index = np.argmax(np.abs(final_state.data))
    final_binary = format(final_index, '03b')
    
    print(f"  |{label}⟩ → |{final_binary}⟩  ({description})")

print("\n✓ Target (qubit 2) only flips when both controls are |1⟩")

# ============================================================================
# PART 3: MULTI-CONTROL GATES (MCX)
# ============================================================================

print("\n" + "="*70)
print("PART 3: MULTI-CONTROL X GATES")
print("="*70)

# ----------------------------------------------------------------------------
# 3 controls (C³X)
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("3-Control X Gate (C³X)")
print("-"*70)

qc_c3x = QuantumCircuit(4)
qc_c3x.mcx([0, 1, 2], 3)  # 3 controls, 1 target

print("\nCircuit with 3 controls:")
print(qc_c3x.draw(output='text'))

print("\nHow it works:")
print("  Controls: qubits 0, 1, 2")
print("  Target: qubit 3")
print("  Flips target ONLY if all 3 controls = |1⟩")

# Test: Initialize to |1110⟩ and |1111⟩
print("\n" + "-"*70)
print("Testing C³X")
print("-"*70)

# Case 1: |1110⟩ (all controls = 1, target = 0)
qc_test1 = QuantumCircuit(4)
qc_test1.x([0, 1, 2])  # Set controls to |1⟩
qc_test1.mcx([0, 1, 2], 3)

state1 = Statevector(qc_test1)
final1 = format(np.argmax(np.abs(state1.data)), '04b')

print(f"\nCase 1: |1110⟩ → |{final1}⟩")
print(f"  Expected: |1111⟩ (target flipped)")
print(f"  Match: {final1 == '1111'} ✓")

# Case 2: |1010⟩ (not all controls = 1)
qc_test2 = QuantumCircuit(4)
qc_test2.x([0, 2])  # Only controls 0 and 2 = |1⟩
qc_test2.mcx([0, 1, 2], 3)

state2 = Statevector(qc_test2)
final2 = format(np.argmax(np.abs(state2.data)), '04b')

print(f"\nCase 2: |1010⟩ → |{final2}⟩")
print(f"  Expected: |1010⟩ (no flip, not all controls = 1)")
print(f"  Match: {final2 == '1010'} ✓")

# ----------------------------------------------------------------------------
# Scaling: Different numbers of controls
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Multi-Control Gates with Different Numbers")
print("-"*70)

control_counts = [1, 2, 3, 4, 5]

print("\nCircuit diagrams for different control counts:")

for n_controls in control_counts:
    qc = QuantumCircuit(n_controls + 1)
    
    if n_controls == 1:
        qc.cx(0, n_controls)  # CNOT
    elif n_controls == 2:
        qc.ccx(0, 1, n_controls)  # Toffoli
    else:
        qc.mcx(list(range(n_controls)), n_controls)  # Multi-control
    
    print(f"\n{n_controls} control(s):")
    print(qc.draw(output='text', fold=-1))

# ============================================================================
# PART 4: DECOMPOSING TOFFOLI INTO CNOTS
# ============================================================================

print("\n" + "="*70)
print("PART 4: TOFFOLI DECOMPOSITION")
print("="*70)

print("\nToffoli is a high-level gate. On real hardware, it's built from:")
print("  - CNOT gates")
print("  - Single-qubit rotations (T, T†, H)")

# ----------------------------------------------------------------------------
# Standard Toffoli decomposition
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Decomposed Toffoli Circuit")
print("-"*70)

qc_decomposed = QuantumCircuit(3)

# Standard decomposition (one of several possible)
qc_decomposed.h(2)
qc_decomposed.cx(1, 2)
qc_decomposed.tdg(2)  # T†
qc_decomposed.cx(0, 2)
qc_decomposed.t(2)
qc_decomposed.cx(1, 2)
qc_decomposed.tdg(2)
qc_decomposed.cx(0, 2)
qc_decomposed.t(1)
qc_decomposed.t(2)
qc_decomposed.cx(0, 1)
qc_decomposed.h(2)
qc_decomposed.t(0)
qc_decomposed.tdg(1)
qc_decomposed.cx(0, 1)

print("\nDecomposed Toffoli (15 gates total):")
print(qc_decomposed.draw(output='text'))

print("\nGate count:")
print(f"  CNOTs: 6")
print(f"  Single-qubit: 9 (H, T, T†)")
print(f"  Total: 15")

# Verify equivalence
qc_standard = QuantumCircuit(3)
qc_standard.ccx(0, 1, 2)

op_standard = Operator(qc_standard)
op_decomposed = Operator(qc_decomposed)

equivalent = np.allclose(op_standard.data, op_decomposed.data)

print(f"\nDecomposed circuit equivalent to CCNOT: {equivalent} ✓")

# ----------------------------------------------------------------------------
# Depth comparison
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Circuit Depth Comparison")
print("-"*70)

# Native Toffoli (hypothetical - if hardware supports it)
qc_native = QuantumCircuit(3)
qc_native.ccx(0, 1, 2)

# Decomposed Toffoli
# (Already created above as qc_decomposed)

print(f"\nNative Toffoli depth: {qc_native.depth()}")
print(f"  (Treated as single gate)")

print(f"\nDecomposed Toffoli depth: {qc_decomposed.depth()}")
print(f"  (Built from CNOTs and single-qubit gates)")

print("\nTrade-off:")
print("  Native: Fast (depth=1) but requires special hardware")
print("  Decomposed: Slower (depth~7) but uses only basic gates")

# ============================================================================
# PART 5: CONTROLLED VERSIONS OF ARBITRARY GATES
# ============================================================================

print("\n" + "="*70)
print("PART 5: CONTROLLED-U FOR ANY GATE")
print("="*70)

print("\nWe can make ANY unitary gate controlled.")
print("Not just X - also H, Z, custom gates, etc.")

# ----------------------------------------------------------------------------
# Controlled-H (CH gate)
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Controlled-Hadamard (CH)")
print("-"*70)

qc_ch = QuantumCircuit(2)
qc_ch.ch(0, 1)  # Control: 0, Target: 1

print("\nControlled-H circuit:")
print(qc_ch.draw(output='text'))

print("\nHow it works:")
print("  If control = |0⟩: target unchanged")
print("  If control = |1⟩: apply H to target")

# Test with superposition on control
qc_test_ch = QuantumCircuit(2)
qc_test_ch.h(0)  # Control in superposition
qc_test_ch.ch(0, 1)  # Controlled-H

state = Statevector(qc_test_ch)

print("\nTest: Control in |+⟩, target in |0⟩")
print(f"Initial: |+0⟩ = (|00⟩ + |10⟩)/√2")
print(f"\nAfter CH:")
print(f"  State vector: {state.data}")

# ----------------------------------------------------------------------------
# Controlled-Z (CZ gate)
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Controlled-Z (CZ)")
print("-"*70)

qc_cz = QuantumCircuit(2)
qc_cz.cz(0, 1)

print("\nControlled-Z circuit:")
print(qc_cz.draw(output='text'))

print("\nSpecial property of CZ:")
print("  CZ is SYMMETRIC - no distinction between control/target")
print("  |11⟩ gets phase flip, others unchanged")

# Show CZ matrix
cz_matrix = Operator(qc_cz).data
print("\nCZ matrix:")
print(cz_matrix.real.astype(int))

print("\nNote: Diagonal matrix!")
print("  |00⟩ → |00⟩")
print("  |01⟩ → |01⟩")
print("  |10⟩ → |10⟩")
print("  |11⟩ → -|11⟩  (phase flip)")

# ----------------------------------------------------------------------------
# Custom controlled gate
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Controlled Custom Gate")
print("-"*70)

print("\nExample: Make a custom rotation controlled")

# Define a custom gate (rotation around Y by π/3)
theta = np.pi / 3
custom_gate = np.array([
    [np.cos(theta/2), -np.sin(theta/2)],
    [np.sin(theta/2), np.cos(theta/2)]
])

print(f"\nCustom gate: Ry({theta:.4f}):")
print(custom_gate)

# Create controlled version
from qiskit.circuit.library import UnitaryGate

qc_custom = QuantumCircuit(2)
custom_unitary = UnitaryGate(custom_gate)
controlled_custom = custom_unitary.control(1)
qc_custom.append(controlled_custom, [0, 1])

print("\nControlled custom gate circuit:")
print(qc_custom.draw(output='text'))

# Verify behavior
qc_test_custom = QuantumCircuit(2)
qc_test_custom.x(0)  # Control = |1⟩
qc_test_custom.append(controlled_custom, [0, 1])

state_custom = Statevector(qc_test_custom)
print(f"\nWith control = |1⟩, target gets rotated:")
print(f"  Final state: {state_custom.data}")

# ============================================================================
# PART 6: PRACTICAL APPLICATIONS
# ============================================================================

print("\n" + "="*70)
print("PART 6: PRACTICAL EXAMPLE - REVERSIBLE COMPUTATION")
print("="*70)

print("\nToffoli can implement classical reversible logic.")
print("Example: Computing AND gate")

# ----------------------------------------------------------------------------
# AND gate using Toffoli
# ----------------------------------------------------------------------------

print("\n" + "-"*70)
print("Classical AND Gate (Quantum Implementation)")
print("-"*70)

print("\nTruth table we want:")
print("\n  a   b  | a AND b")
print("  ----------------")
print("  0   0  |    0")
print("  0   1  |    0")
print("  1   0  |    0")
print("  1   1  |    1")

print("\nImplementation:")
print("  Use Toffoli with:")
print("  - Controls: a, b (inputs)")
print("  - Target: initialized to |0⟩ (output)")

test_inputs = [
    ([0, 0], "0 AND 0 = 0"),
    ([0, 1], "0 AND 1 = 0"),
    ([1, 0], "1 AND 0 = 0"),
    ([1, 1], "1 AND 1 = 1"),
]

print("\nTesting:")
for inputs, description in test_inputs:
    qc = QuantumCircuit(3, 1)
    
    # Set inputs
    for i, val in enumerate(inputs):
        if val == 1:
            qc.x(i)
    
    # Compute AND (target starts at |0⟩)
    qc.ccx(0, 1, 2)
    
    # Measure output
    qc.measure(2, 0)
    
    # Run
    result = AerSimulator().run(qc, shots=1).result()
    output = list(result.get_counts().keys())[0]
    
    print(f"  {description} → measured: {output} ✓")



MULTI-QUBIT CONTROLLED GATES

PART 1: TOFFOLI GATE - BUILDING THE MATRIX

----------------------------------------------------------------------
Building Toffoli (CCNOT) Matrix
----------------------------------------------------------------------

Toffoli (CCNOT) matrix:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

Structure:
  - Mostly identity (7x7 block)
  - Only last 2x2 block is swapped
  - This corresponds to flipping target when both controls = |1⟩

----------------------------------------------------------------------
Verifying Unitarity
----------------------------------------------------------------------

CCNOT is unitary: True ✓
CCNOT is self-inverse: True ✓
  (Applying Toffoli twice returns to original state)

----------------------------------------------------------------------
Verifying Truth Table
----------------------------------------------------------------